version: '3'
services:
    # minio:
    #     image: minio/minio
    #     container_name: minio
    #     ports:
    #         - '9000:9000'
    #         - '9001:9001'
    #     volumes:
    #         - ./storage:/data
    #     environment:
    #         MINIO_ROOT_USER: minio_admin
    #         MINIO_ROOT_PASSWORD: cdef3456@A
    #     command: server --console-address ":9001" /data
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
            - 8080:8080
            - 50000:50000
        container_name: fb-clone-jenkins
        volumes:
            - ~/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/local/bin/docker
    rabbitmq:
        image: rabbitmq:management
        container_name: fb-clone-rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=${RMQ_USERNAME}
            - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}
            - RABBITMQ_DEFAULT_VHOST=${RMQ_VHOST}
        ports:
            - '5672:5672'
            - '15672:15672'
    redis:
        image: 'redis:alpine'
        container_name: fb-clone-redis
        ports:
            - '6379:6379'
        # environment:
        #     - REDIS_PASSWORD=${REDIS_PASSWORD}
    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: fb-clone-redis-commander
        restart: always
        environment:
            REDIS_HOSTS: redis
            REDIS_HOST: redis
            REDIS_PORT: redis:6379
            # REDIS_PASSWORD: ${REDIS_PASSWORD}
        ports:
            - 8081:8080
    postgres:
        image: postgres
        container_name: fb-clone-postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            TZ: 'GMT'
            PGTZ: 'GMT'
        ports:
            - '5432:5432'
        volumes:
            - postgres:/data/postgres
        env_file:
            - .env
    pgadmin:
        container_name: fb-clone-pgadmin
        image: dpage/pgadmin4
        ports:
            - '8082:80'
        volumes:
            - pgadmin:/root/.pgadmin
        env_file:
            - .env
        links:
            - postgres
volumes:
    postgres:
        driver: local
    pgadmin:
        driver: local
    rmq_data:
        driver: local
