import { ENUM_PAGINATION_ORDER_DIRECTION_TYPE } from 'src/core/pagination/constants/pagination.enum.constant';

export const NOTIFICATION_DEFAULT_ORDER_BY = 'createdAt';
export const NOTIFICATION_DEFAULT_ORDER_DIRECTION =
    ENUM_PAGINATION_ORDER_DIRECTION_TYPE.ASC;
export const NOTIFICATION_DEFAULT_PER_PAGE = 20;
export const NOTIFICATION_DEFAULT_AVAILABLE_ORDER_BY = ['createdAt'];
export const NOTIFICATION_DEFAULT_AVAILABLE_SEARCH = [];
